# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vincent/Etudes/M1/S2/PA/pas-cman

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vincent/Etudes/M1/S2/PA/pas-cman

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vincent/Etudes/M1/S2/PA/pas-cman/CMakeFiles /home/vincent/Etudes/M1/S2/PA/pas-cman/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vincent/Etudes/M1/S2/PA/pas-cman/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PacMan

# Build rule for target.
PacMan: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PacMan
.PHONY : PacMan

# fast build rule for target.
PacMan/fast:
	$(MAKE) -f CMakeFiles/PacMan.dir/build.make CMakeFiles/PacMan.dir/build
.PHONY : PacMan/fast

pacman.o: pacman.cpp.o

.PHONY : pacman.o

# target to build an object file
pacman.cpp.o:
	$(MAKE) -f CMakeFiles/PacMan.dir/build.make CMakeFiles/PacMan.dir/pacman.cpp.o
.PHONY : pacman.cpp.o

pacman.i: pacman.cpp.i

.PHONY : pacman.i

# target to preprocess a source file
pacman.cpp.i:
	$(MAKE) -f CMakeFiles/PacMan.dir/build.make CMakeFiles/PacMan.dir/pacman.cpp.i
.PHONY : pacman.cpp.i

pacman.s: pacman.cpp.s

.PHONY : pacman.s

# target to generate assembly for a file
pacman.cpp.s:
	$(MAKE) -f CMakeFiles/PacMan.dir/build.make CMakeFiles/PacMan.dir/pacman.cpp.s
.PHONY : pacman.cpp.s

src/Ghost.o: src/Ghost.cpp.o

.PHONY : src/Ghost.o

# target to build an object file
src/Ghost.cpp.o:
	$(MAKE) -f CMakeFiles/PacMan.dir/build.make CMakeFiles/PacMan.dir/src/Ghost.cpp.o
.PHONY : src/Ghost.cpp.o

src/Ghost.i: src/Ghost.cpp.i

.PHONY : src/Ghost.i

# target to preprocess a source file
src/Ghost.cpp.i:
	$(MAKE) -f CMakeFiles/PacMan.dir/build.make CMakeFiles/PacMan.dir/src/Ghost.cpp.i
.PHONY : src/Ghost.cpp.i

src/Ghost.s: src/Ghost.cpp.s

.PHONY : src/Ghost.s

# target to generate assembly for a file
src/Ghost.cpp.s:
	$(MAKE) -f CMakeFiles/PacMan.dir/build.make CMakeFiles/PacMan.dir/src/Ghost.cpp.s
.PHONY : src/Ghost.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... PacMan"
	@echo "... pacman.o"
	@echo "... pacman.i"
	@echo "... pacman.s"
	@echo "... src/Ghost.o"
	@echo "... src/Ghost.i"
	@echo "... src/Ghost.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

