#ifndef MAP_H
#define MAP_H

enum class MTYPE {
    PACMAN,
    GHOST,
    EMPTY,
    WALL,
    DOOR,
    ITEM,
    TP,
};

class Map {
public:
    
    MTYPE map[27][21] = {
            {MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::EMPTY,MTYPE::EMPTY,MTYPE::EMPTY,MTYPE::EMPTY,MTYPE::EMPTY,MTYPE::EMPTY,MTYPE::EMPTY,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::EMPTY,MTYPE::WALL,MTYPE::DOOR,MTYPE::DOOR,MTYPE::DOOR,MTYPE::WALL,MTYPE::EMPTY,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::EMPTY,MTYPE::WALL,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::WALL,MTYPE::EMPTY,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::WALL},
            {MTYPE::TP,MTYPE::EMPTY,MTYPE::EMPTY,MTYPE::EMPTY,MTYPE::EMPTY,MTYPE::ITEM,MTYPE::EMPTY,MTYPE::EMPTY,MTYPE::WALL,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::WALL,MTYPE::EMPTY,MTYPE::EMPTY,MTYPE::ITEM,MTYPE::EMPTY,MTYPE::EMPTY,MTYPE::EMPTY,MTYPE::EMPTY,MTYPE::TP},
            {MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::EMPTY,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::EMPTY,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::EMPTY,MTYPE::EMPTY,MTYPE::EMPTY,MTYPE::EMPTY,MTYPE::EMPTY,MTYPE::EMPTY,MTYPE::EMPTY,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::EMPTY,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::ITEM,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::ITEM,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL},
    };

    template <typename T>
    MTYPE getCurrentTileType(const T& gameObject) const;
};

#endif