#ifndef MAP_H
#define MAP_H

enum class MTYPE {
    COIN,
    WALL,
    DOOR,
    BCOIN,
    EMPTY,
    TPR,
    TPL
};

class Map {
public:
    
    MTYPE map[27][21] = {
            {MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::BCOIN,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::BCOIN,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::EMPTY,MTYPE::EMPTY,MTYPE::EMPTY,MTYPE::EMPTY,MTYPE::EMPTY,MTYPE::EMPTY,MTYPE::EMPTY,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::EMPTY,MTYPE::WALL,MTYPE::DOOR,MTYPE::DOOR,MTYPE::DOOR,MTYPE::WALL,MTYPE::EMPTY,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::EMPTY,MTYPE::WALL,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::WALL,MTYPE::EMPTY,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::WALL},
            {MTYPE::TPL,MTYPE::EMPTY,MTYPE::EMPTY,MTYPE::EMPTY,MTYPE::EMPTY,MTYPE::COIN,MTYPE::EMPTY,MTYPE::EMPTY,MTYPE::WALL,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::WALL,MTYPE::EMPTY,MTYPE::EMPTY,MTYPE::COIN,MTYPE::EMPTY,MTYPE::EMPTY,MTYPE::EMPTY,MTYPE::EMPTY,MTYPE::TPR},
            {MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::EMPTY,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::EMPTY,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::EMPTY,MTYPE::EMPTY,MTYPE::EMPTY,MTYPE::EMPTY,MTYPE::EMPTY,MTYPE::EMPTY,MTYPE::EMPTY,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::BCOIN,MTYPE::COIN,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::EMPTY,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::COIN,MTYPE::BCOIN,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::COIN,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::COIN,MTYPE::WALL},
            {MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL,MTYPE::WALL},
    };

    template <typename T>
    MTYPE getCurrentTileType(const T& gameObject) const;
};

#endif