#ifndef MAP_H
#define MAP_H

enum MTYPE {
    COIN,
    WALL,
    DOOR,
    BCOIN,
    EMPTY,
    TPR,
    TPL,

};

class Map {
public:
    MTYPE map[27][21] = {
            {WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL},
            {WALL,COIN,COIN,COIN,COIN,COIN,COIN,COIN,COIN,COIN,WALL,COIN,COIN,COIN,COIN,COIN,COIN,COIN,COIN,COIN,WALL},
            {WALL,COIN,WALL,WALL,WALL,COIN,WALL,WALL,WALL,COIN,WALL,COIN,WALL,WALL,WALL,COIN,WALL,WALL,WALL,COIN,WALL},
            {WALL,BCOIN,WALL,COIN,WALL,COIN,WALL,COIN,WALL,COIN,WALL,COIN,WALL,COIN,WALL,COIN,WALL,COIN,WALL,BCOIN,WALL},
            {WALL,COIN,WALL,WALL,WALL,COIN,WALL,WALL,WALL,COIN,WALL,COIN,WALL,WALL,WALL,COIN,WALL,WALL,WALL,COIN,WALL},
            {WALL,COIN,COIN,COIN,COIN,COIN,COIN,COIN,COIN,COIN,COIN,COIN,COIN,COIN,COIN,COIN,COIN,COIN,COIN,COIN,WALL},
            {WALL,COIN,WALL,WALL,WALL,COIN,WALL,COIN,WALL,WALL,WALL,WALL,WALL,COIN,WALL,COIN,WALL,WALL,WALL,COIN,WALL},
            {WALL,COIN,WALL,WALL,WALL,COIN,WALL,COIN,WALL,WALL,WALL,WALL,WALL,COIN,WALL,COIN,WALL,WALL,WALL,COIN,WALL},
            {WALL,COIN,COIN,COIN,COIN,COIN,WALL,COIN,COIN,COIN,WALL,COIN,COIN,COIN,WALL,COIN,COIN,COIN,COIN,COIN,WALL},
            {WALL,WALL,WALL,WALL,WALL,COIN,WALL,WALL,WALL,COIN,WALL,COIN,WALL,WALL,WALL,COIN,WALL,WALL,WALL,WALL,WALL},
            {WALL,COIN,COIN,COIN,WALL,COIN,WALL,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,WALL,COIN,WALL,COIN,COIN,COIN,WALL},
            {WALL,COIN,COIN,COIN,WALL,COIN,WALL,EMPTY,WALL,DOOR,DOOR,DOOR,WALL,EMPTY,WALL,COIN,WALL,COIN,COIN,COIN,WALL},
            {WALL,COIN,COIN,COIN,WALL,COIN,WALL,EMPTY,WALL,COIN,COIN,COIN,WALL,EMPTY,WALL,COIN,WALL,COIN,COIN,COIN,WALL},
            {TPL,EMPTY,EMPTY,EMPTY,EMPTY,COIN,EMPTY,EMPTY,WALL,COIN,COIN,COIN,WALL,EMPTY,EMPTY,COIN,EMPTY,EMPTY,EMPTY,EMPTY,TPR},
            {WALL,WALL,WALL,WALL,WALL,COIN,WALL,EMPTY,WALL,WALL,WALL,WALL,WALL,EMPTY,WALL,COIN,WALL,WALL,WALL,WALL,WALL},
            {WALL,COIN,COIN,COIN,WALL,COIN,WALL,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,WALL,COIN,WALL,COIN,COIN,COIN,WALL},
            {WALL,COIN,COIN,COIN,WALL,COIN,WALL,COIN,WALL,WALL,WALL,WALL,WALL,COIN,WALL,COIN,WALL,COIN,COIN,COIN,WALL},
            {WALL,WALL,WALL,WALL,WALL,COIN,WALL,COIN,WALL,WALL,WALL,WALL,WALL,COIN,WALL,COIN,WALL,WALL,WALL,WALL,WALL},
            {WALL,COIN,COIN,COIN,COIN,COIN,COIN,COIN,COIN,COIN,WALL,COIN,COIN,COIN,COIN,COIN,COIN,COIN,COIN,COIN,WALL},
            {WALL,COIN,WALL,WALL,WALL,COIN,WALL,WALL,WALL,COIN,WALL,COIN,WALL,WALL,WALL,COIN,WALL,WALL,WALL,COIN,WALL},
            {WALL,BCOIN,COIN,COIN,WALL,COIN,COIN,COIN,COIN,COIN,EMPTY,COIN,COIN,COIN,COIN,COIN,WALL,COIN,COIN,BCOIN,WALL},
            {WALL,WALL,WALL,COIN,WALL,COIN,WALL,COIN,WALL,WALL,WALL,WALL,WALL,COIN,WALL,COIN,WALL,COIN,WALL,WALL,WALL},
            {WALL,WALL,WALL,COIN,WALL,COIN,WALL,COIN,WALL,WALL,WALL,WALL,WALL,COIN,WALL,COIN,WALL,COIN,WALL,WALL,WALL},
            {WALL,COIN,COIN,COIN,COIN,COIN,WALL,COIN,COIN,COIN,WALL,COIN,COIN,COIN,WALL,COIN,COIN,COIN,COIN,COIN,WALL},
            {WALL,COIN,WALL,WALL,WALL,WALL,WALL,WALL,WALL,COIN,WALL,COIN,WALL,WALL,WALL,WALL,WALL,WALL,WALL,COIN,WALL},
            {WALL,COIN,COIN,COIN,COIN,COIN,COIN,COIN,COIN,COIN,COIN,COIN,COIN,COIN,COIN,COIN,COIN,COIN,COIN,COIN,WALL},
            {WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL},
    }
};

#endif